functionsDirectory = "/home/shaban/Desktop/mywebsite/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
plugins = []

[build]
publish = "/home/shaban/Desktop/mywebsite"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Static site - no build step needed'"
functions = "/home/shaban/Desktop/mywebsite/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm start || python3 -m http.server 8000"
targetPort = 8000.0
framework = "#static"

[functions]

[functions."*"]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "no-transform"
Nelson-Edge-Cache-Control = "no-transform"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "no-transform, public, max-age=31536000"
Nelson-Edge-Cache-Control = "no-transform"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]